server:
  address: 127.0.0.1
  port: 8080

course-management:
  url: http://localhost:8081

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/UserDB
    username: postgres
    password: 307t0HrY
  flyway:
    baseline-on-migrate: true
  jpa:
    properties:
      hibernate:
        show_sql: true
        hbm2ddl:
          auto: create
  mail:
    host: app.debugmail.io
    port: 25
    username: 372b2d22-a9ad-4180-8b42-4769133dff7c
    password: b4d1aebe-407c-4312-ad95-cd4c8cc49b7d
    from: no-reply@course-space.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
