#server:
# address: 127.0.0.1
# port: 8080

course_management:
  url: ${COURSE_MANAGEMENT_URL:http://localhost:8081}

spring:
  profiles:
    default: prod
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5434/UserDB
    username: postgres
    password: 307t0HrY
  flyway:
    baseline-on-migrate: true

  mail:
    host: app.debugmail.io
    port: 25
    username: 372b2d22-a9ad-4180-8b42-4769133dff7c
    password: b4d1aebe-407c-4312-ad95-cd4c8cc49b7d
    from: no-reply@course-space.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  kafka:
    consumer:
      bootstrap_servers: kafka:9092
---
spring:
  jpa:
    properties:
      show-sql: true
      hibernate:
        hbm2ddl:
          auto: none