server:
  address: 127.0.0.1
  port: 8080

course-management:
  url: http://localhost:8081

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/UserDB
    username: postgres
    password: 307t0HrY
  flyway:
    baseline-on-migrate: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        hbm2ddl:
          auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: vladislav.niiazov@gmail.com
    password: a4X76u3PDI
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

