-- Создание таблицы 'role'
CREATE TABLE role
(
    id          INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name        VARCHAR(50) NOT NULL UNIQUE,
    description TEXT,
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Создание таблицы 'user'
CREATE TABLE "user"
(
    id         INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username   VARCHAR(100) NOT NULL,
    email      VARCHAR(255) NOT NULL,
    password   VARCHAR(255) NOT NULL,
    status     VARCHAR(20) DEFAULT 'ACTIVE',
    created_at TIMESTAMP   DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP   DEFAULT CURRENT_TIMESTAMP
);

-- Создание таблицы 'profile'
CREATE TABLE profile
(
    id            INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id       INT UNIQUE NOT NULL,
    full_name     VARCHAR(255),
    gender        VARCHAR(10),
    date_of_birth DATE,
    address       TEXT,
    phone_number  VARCHAR(50),
    avatar_url    VARCHAR(255),
    FOREIGN KEY (user_id) REFERENCES "user" (id)
);

-- Создание связующей таблицы 'user_role'
CREATE TABLE user_role
(
    user_id INT,
    role_id INT,
    PRIMARY KEY (user_id, role_id),
    FOREIGN KEY (user_id) REFERENCES "user" (id),
    FOREIGN KEY (role_id) REFERENCES role (id)
);

-- Создание таблицы 'user_activation_token'
CREATE TABLE user_activation_token
(
    id              INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id         INT          NOT NULL,
    token           VARCHAR(255) NOT NULL,
    expiration_time TIMESTAMP    NOT NULL,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES "user" (id)
);